specVersion: "1.0.0"

name: "soroban-subql-starter"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-concordium"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your new Concordium Soroban Future Network SubQuery project"
repository: "https://github.com/subquery/concordium-subql-starter"

schema:
  file: "./schema.graphql"

network:
  # Concordium and Soroban uses the network passphrase as the chainId
  # 'Public Global Concordium Network ; September 2015' for mainnet
  # 'Test SDF Future Network ; October 2022' for Future Network
  chainId: "4221332d34e1694168c2a0c0b3fd0f273809612cb13d000d5c2e00e85f50f796"
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  endpoint: ["node.testnet.concordium.com:20000"]
  # Recommended to provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://gx.api.subquery.network/sq/subquery/eth-dictionary"

dataSources:
  - kind: concordium/Runtime
    startBlock: 490000 # This is the start block from which you begin indexing
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTransaction
          kind: concordium/TransactionHandler
          filter:
            type: 'accountTransaction'
            values:
              transactionType: 'transfer'
        - handler: handleTransactionEvent
          kind: concordium/TransactionEventHandler
          filter:
            type: 'Updated'
        - handler: handleSpecialEvent
          kind: concordium/SpecialEventHandler
          filter:
            type: 'blockAccrueReward'